# Generated by Django 4.2.3 on 2023-08-31 20:35

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[projects.validators.validate_profile],
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        validators=[projects.validators.validate_profile]
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        validators=[projects.validators.validate_profile]
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        validators=[projects.validators.validate_profile]
                    ),
                ),
            ],
        ),
    ]
